config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :short_urls
  root to: "short_urls#index"

  get 'original', to: 'short_urls#original'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/short_url.rb
class ShortUrl < ApplicationRecord
	validates_uniqueness_of :short_url

	ALPHABET = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789".split(//)
	  # make your own alphabet using:	  

	def self.bijective_encode(i) # getting short URL from unique_id	  
	  # converting number to string
	  return ALPHABET[0] if i == 0
	  s = ''
	  base = ALPHABET.length
	  while i > 0
	    s << ALPHABET[i.modulo(base)]
	    i /= base
	  end
	  s.reverse
	end

	def self.bijective_decode(s) # Getting the unique_id back for Identification
	  # converting from string to number for identification	
	  return nil if s.include? "."
	  i = 0
	  base = ALPHABET.length
	  s.each_char { |c| i = i * base + ALPHABET.index(c) }
	  i
	end

	def self.get_host_without_www(url) # Return Host name of URL  
	  if url.include? "http://" or url.include? "https://"
	  	 uri = URI.parse("#{URI.encode(url.strip)}")
	  else
	  	uri = URI.parse("http://#{URI.encode(url.strip)}")	  	
	  end	  

	  host = uri.host.downcase
	  host.start_with?('www.') ? host[4..-1] : host	  	 	  
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/short_urls_controller.rb
class ShortUrlsController < ApplicationController

	def index
		if params[:search]			
			key = params[:search].gsub('https://secure-ravine-12192.herokuapp.com/original?url=','') # RegEx, to get only my short_url 			
			short_url_id = ShortUrl.bijective_decode(key) 
			@urls = ShortUrl.where(unique_key: short_url_id)
		else		
			@urls = ShortUrl.all.order(count: :desc).limit(100) # All URLs order in descending order and limit 100
		end
	end

	def new
	end

	def create		
		if params[:search].present?			
			url = ShortUrl.get_host_without_www(params[:search]) # RegEx, to get only host name 'google' from 'www.google.com'
			uri = URI.parse(URI.encode(params[:search].strip))
			
			if uri.instance_of?(URI::Generic)
    			uri = URI::HTTP.build({:host => uri.to_s}) 
			end
			query = "#{uri.path}#{uri.query}#{uri.fragment}"
						

			if ShortUrl.last # Auto Increment my unique_id
				last_key = ShortUrl.last.unique_key+1 
				short_url   = ShortUrl.bijective_encode(last_key)
			else
				last_key = 125
				short_url = ShortUrl.bijective_encode(last_key)
			end

			if record = ShortUrl.find_by(url: url) # same url access twice				
				record.count = record.count + 1
				record.save
			else
				ShortUrl.create(url: url, short_url: short_url, count: 1, unique_key: last_key, query_string: query) # Create New short_url 
			end
		end

		redirect_to short_urls_path	
	end

	def original # For clicking on short_url and redirect to Original URL, along with counter increament 
		if params[:url].present? 
			single_url = ShortUrl.find_by(short_url: params[:url])	
			single_url.count = single_url.count+1
			single_url.save	
			url_id = ShortUrl.bijective_decode(single_url.short_url)
			host_url = "http://www.#{ShortUrl.find_by(unique_key: url_id).try(:url)}#{single_url.query_string}"
			redirect_to host_url
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/short_urls_helper.rb
module ShortUrlsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Stock" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top navbar-inverse">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" id="style-text" href="#">ShortYourUrl</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Add Url", new_short_url_path %></li>
            <li><%= link_to "Url History", short_urls_path  %></li>            
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>        
        </div><!--/span-->
      </div><!--/row-->     

    </div> <!-- /container -->

  </body>
</html>

app/views/short_urls/index.html.erb
<h1>Recently Access URLs</h1></br>

<p>Write Your Short URL for Searching</p>

<%= form_tag "short_urls#index", method: :get do %>
	<%= text_field_tag :search %>
	<%= submit_tag "Submit", class: "btn btn-primary" %>
<% end %>

<table class="table table-striped">
	<thead class="thead-inverse">
		<th>URL</th>
		<th></th>
		<th>Short Url</th>
		<th>Number of Times the URL is Searched</th>		
	</thead>
	<tbody>
	<% @urls.each do |single_url| %>	
		<tr>
			<td><%= single_url.url %></td>
			<td></td>			
			<td><%= link_to "https://secure-ravine-12192.herokuapp.com/original?url=#{single_url.short_url}", original_path(:url=>  single_url.short_url), target: :blank %></td>
			<td><%= single_url.count %></td>
		</tr>
	<% end %>
		
	</tbody>
</table>

app/views/short_urls/new.html.erb
<div class="form-style">
	<h2>Write a Long URL to make it Short</h2>

	<%= form_tag action: 'create', method: :post do %>
		<%= text_field_tag :search %>
		<%= submit_tag "Submit", class: "btn btn-primary" %>
	<% end %>
	
	<br><span> Write in the form (www.xyz.com Or http://www.abc.com)</span>
</div>